version: "3.9"

services:
  server:
    build: .
    network_mode: "host"
    volumes:
      - "/data/logs/rs_server:/usr/spider/logs"
    container_name: rs_server
    entrypoint: ["/usr/local/bin/gunicorn", "-c", "gunicorn.py", "--pythonpath", "/usr/spider", "wsgi:app"]
