version: "3.9"

services:
  server:
    build: .
    network_mode: "host"
    volumes:
      - "/data/logs/zxgk_server:/usr/spider/logs"
    container_name: zxgk_server
    entrypoint: ["node", "/usr/spider/zxgk/node_server.js"]